//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace com.fabioscagliola.CsvReader.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("com.fabioscagliola.CsvReader.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keys not read. Did you invoke the Load method?.
        /// </summary>
        public static string GetStringValueException1 {
            get {
                return ResourceManager.GetString("GetStringValueException1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Values not read. Did you invoke the ReadLine method?.
        /// </summary>
        public static string GetStringValueException2 {
            get {
                return ResourceManager.GetString("GetStringValueException2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key &quot;{0}&quot; not found..
        /// </summary>
        public static string GetStringValueException3 {
            get {
                return ResourceManager.GetString("GetStringValueException3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot read field names. Is the file empty?.
        /// </summary>
        public static string LoadException1 {
            get {
                return ResourceManager.GetString("LoadException1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of values does not match the number of keys..
        /// </summary>
        public static string ReadLineException1 {
            get {
                return ResourceManager.GetString("ReadLineException1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The underlying stream reader is not initialized. Did you invoke the Load method?.
        /// </summary>
        public static string ReadLineToException1 {
            get {
                return ResourceManager.GetString("ReadLineToException1", resourceCulture);
            }
        }
    }
}
